### ISSUE TITLE
Review the enviroment page

### ISSUE THREAD

**Issue by sambarza** [cheshire-cat-ai/docs#125]
The enviroment page is not up to date:
https://cheshire-cat-ai.github.io/docs/administrators/env-variables/

For example CORE_HOST and CORE_PORT are no more relevant

**Comment by pieroit** [comment]
`CORE_PORT` still relevnt because indeed you can change the core port!
For example have the cat under `localhost:222`

**Comment by pieroit** [comment]
Env variables documented, devided by category, with a guide on how to set them up
https://cheshire-cat-ai.github.io/docs/production/administrators/env-variables/
