### ISSUE TITLE
Any web UI？

### ISSUE THREAD

**Issue by thinker007** [cheshire-cat-ai/docs#147]
Any web User interface to interact this project？

**Comment by pieroit** [comment]
> Any web User interface to interact this project？

We have an [admin panel](https://cheshire-cat-ai.github.io/docs/technical/basics/admin/admin-interface/)
Public facing UIs or any other client can be realized according to your needs (we have client libs in many languages).

**Comment by thinker007** [comment]
> > Any web User interface to interact this project？
> 
> We have an [admin panel](https://cheshire-cat-ai.github.io/docs/technical/basics/admin/admin-interface/) Public facing UIs or any other client can be realized according to your needs (we have client libs in many languages).

Thanks for the reply

I mean more sophisticate UI just like ChatGPT web or lobechat
