### ISSUE TITLE
List open source client apps/widgets

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/docs#153]
We've got client apps for Telegram and Discord, plus a series of browser widgets (vuejs, vanilla, alpine, react)

Those could be listed under `clients` as the client libs

**Comment by kodaline** [comment]
@pieroit can I propose a PR on this?

**Comment by kodaline** [comment]
I imagine something like:

- Client Apps
  - Telegram
  - Discord
  - ...
- Client Widgets
  - TS
  - Alpine
  - ...
 
 Currently we have:
![Screenshot from 2024-06-01 09-48-19](https://github.com/cheshire-cat-ai/docs/assets/9247877/73089614-aeb7-44d4-98e1-cbf08b0120b0)

Would you put a general Clients section so having:

- Clients
  - Libraries
  - Apps
  - Widgets
  - etc.

Or leave it as it is? And just add a couple sections `Client Apps` and `Client Widgets` as global sections under `Production`, as `Client Libraries` are now?

**Comment by pieroit** [comment]
> @pieroit I imagine something like:
> 
> * Client Apps
>   
>   * Telegram
>   * Discord
>   * ...
> * Client Widgets
>   
>   * TS
>   * Alpine
>   * ...
> 
> Currently we have: ![Screenshot from 2024-06-01 09-48-19](https://private-user-images.githubusercontent.com/9247877/335786152-73089614-aeb7-44d4-98e1-cbf08b0120b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzYzMzUsIm5iZiI6MTcxNzIzNjAzNSwicGF0aCI6Ii85MjQ3ODc3LzMzNTc4NjE1Mi03MzA4OTYxNC1hZWI3LTQ0ZDQtOThlMS1jYmYwOGIwMTIwYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDFUMTAwMDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2QxZjAwZTMyYjdlMzE1Y2UxN2MzM2YxNDI0YzcwY2ZmNjRiZTU5ZWE2ZTNiMDljYzIzOWYxOWMxMTJlOTcyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Zh7lQTVpis3VvncmTGmVto15KSwW6QBJ9Yl0PR0hI-g)
> 
> Would you put a general Clients section so having:
> 
> * Clients
>   
>   * Libraries
>   * Apps
>   * Widgets
>   * etc.
> 
> Or leave it as it is? And just add a couple sections `Client Apps` and `Client Widgets` as global sections under `Production`, as `Client Libraries` are now?

This is a great idea, a `Clients` section under `Production` with libs, apps and widgets

I would also have this pages just with a small reference and a link to the repos, to make our docs lighter.

For example `Clients/Libraries` listing all the clients in a single page, instead of one page per library

Similar to this:
http://docs.mongodb.com/manual/applications/drivers

We only give a reference so client libs maintainers can update docs on their own

**Comment by kodaline** [comment]
> This is a great idea, a `Clients` section under `Production` with libs, apps and widgets
> 
> I would also have this pages just with a small reference and a link to the repos, to make our docs lighter.
> 

I agree, otherwise we should monitor the clients' docs and update ours too. It should be a responsibility of who created the client to keep up to date their docs on the repo
> For example `Clients/Libraries` listing all the clients in a single page, instead of one page per library
> 

I like the idea of having them on a single page, more clean
> Similar to this: http://docs.mongodb.com/manual/applications/drivers
> 

looks great!
> We only give a reference so client libs maintainers can update docs on their own

Top
