### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Flecart** [cheshire-cat-ai/docs#154]
This link does not exist: https://cheshirecat.ai/2023/08/19/custom-large-language-model/

From here
![image](https://github.com/cheshire-cat-ai/docs/assets/63465494/ab6b0efe-6564-4519-9203-f38e60af68d3)

**Comment by nicola-corbellini** [comment]
Thank you, I've made a PR to fix the link

**Comment by Flecart** [comment]
@nicola-corbellini Come è il pycon :)?

**Comment by nicola-corbellini** [comment]
@Flecart credo tu mi confonda con @nickprock

**Comment by Flecart** [comment]
Sì lol. Ho sparato un nicola xD.

**Comment by nickprock** [comment]
Figo! Oggi ho parlato con il CEO di Argilla(del gattone), la CEO di Spacy e un core dev di Scikit learn. A parte questo il gattone piace a tutti, tanto hype
