### ISSUE TITLE
Environment Variables .env

### ISSUE THREAD

**Issue by ap-70** [cheshire-cat-ai/docs#176]
HI! Do you think it could be useful to integrate this information on how to activate reading of the .env file?

![Schermata del 2024-07-20 06-51-28](https://github.com/user-attachments/assets/b70409b8-5104-4806-acb5-33be2c634a95)
![Schermata del 2024-07-20 06-57-34](https://github.com/user-attachments/assets/0e3f3e7e-a6a0-4814-9d9b-6ad54c72e630)

**Comment by pieroit** [comment]
> HI! Do you think it could be useful to integrate this information on how to activate reading of the .env file?
> 
> ![Schermata del 2024-07-20 06-51-28](https://private-user-images.githubusercontent.com/168991571/350664807-b70409b8-5104-4806-acb5-33be2c634a95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzA3NjAsIm5iZiI6MTcyMTQ3MDQ2MCwicGF0aCI6Ii8xNjg5OTE1NzEvMzUwNjY0ODA3LWI3MDQwOWI4LTUxMDQtNDgwNi1hY2I1LTMzYmUyYzYzNGE5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxMDE0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzQ3N2I3YjM3ZWZlNGI0YjZlZTViZTc2Mjc5ZDdmOWU2MmY1ZmVlN2ZkYzNlZjY2NTIwYzAyMmRlNmRiZTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4DlADXrvmP5kE4Ea4M0aMJ2U8CFZB17MFBzxi1iU7z0) ![Schermata del 2024-07-20 06-57-34](https://private-user-images.githubusercontent.com/168991571/350664812-0e3f3e7e-a6a0-4814-9d9b-6ad54c72e630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzA3NjAsIm5iZiI6MTcyMTQ3MDQ2MCwicGF0aCI6Ii8xNjg5OTE1NzEvMzUwNjY0ODEyLTBlM2YzZTdlLWE2YTAtNDgxNC05ZDliLTZhZDU0YzcyZTYzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxMDE0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWE3MTdiMWRkZmIxNzdmMGVkZWYxODBmYWMyMjRhNzM0ZjBhZDVkYjAyNzNiNjUwNzAzZDAxYjE4ODIxMDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m5RsJMHruHX7Q9JzaqBDy72oEwOt6kXNE_VHiY_sZ00)

Agree!
- create .env (same folder as compose.yml)
- use `env_file` in the compose

Can you do a PR?
Thanks

**Comment by ap-70** [comment]
I had to get help from chatgpt to understand what the letters PR meant...(Pull Request) I understood in general how it works but I didn't know how to do it...

**Comment by ap-70** [comment]
I tried to do a PR... let's hope for good...

**Comment by pieroit** [comment]
There you go

https://cheshire-cat-ai.github.io/docs/production/administrators/env-variables/

**Comment by ap-70** [comment]
Good! Clear and complete...
