### ISSUE TITLE
error in env guide QDRANT_HOST to CCAT_QDRANT_HOST ?

### ISSUE THREAD

**Issue by riccardoniccoliwetechs** [cheshire-cat-ai/docs#180]
error in ?
https://cheshire-cat-ai.github.io/docs/production/administrators/docker-compose/

Add this enviroment variables in your .env file:

# Qdrant server
QDRANT_HOST=cheshire_cat_vector_memory # <url of the cluster>
QDRANT_PORT=6333 # <port of the cluster, usually 6333>
QDRANT_API_KEY="" # optional <api-key>

# Qdrant server
CCAT_QDRANT_HOST=cheshire_cat_vector_memory # <url of the cluster>
CCAT_QDRANT_PORT=6333 # <port of the cluster, usually 6333>
CCAT_QDRANT_API_KEY="" # optional <api-key>

**Comment by pieroit** [comment]
You are right, can you fix with a PR on `main`?

**Comment by riccardoniccoliwetechs** [comment]
Update docker-compose.md #181

**Comment by riccardoniccoliwetechs** [comment]
change required
