### ISSUE TITLE
Document the Log system

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/docs#27]
Missing documentation about the logging system, the log levels and how to set it in the `.env` file.

**Comment by kodaline** [comment]
@nicola-corbellini can I document this one?

**Comment by nicola-corbellini** [comment]
absolutely

**Comment by nicola-corbellini** [comment]
@kodaline where would you put it? 
What about a `Debugging` chapter with a `Logging` page? You could also reference [this page](https://cheshire-cat-ai.github.io/docs/administrators/env-variables/#log_level)

**Comment by kodaline** [comment]
> @kodaline where would you put it? What about a `Debugging` chapter with a `Logging` page in the `Plugin` section? You could also reference [this page](https://cheshire-cat-ai.github.io/docs/administrators/env-variables/#log_level)

Or `Debugging` under `Framework`? It's related more to the Cat itself, and not limited to the `Plugins`, I don't want to confuse people 😄

**Comment by nicola-corbellini** [comment]
What leaves me skeptical is that under `Framework` there are more abstract concepts and no code (devs use code and logging only in the plugins), but it's true that debugging is something related to the whole Cat. 

I'm not sure but my take is: if we will extend the `Debugging` chapter with something more, I agree with you; if under `Debugging` we'll have only `Logging`, I'll say to just put `Logging` in plugins.

**Comment by kodaline** [comment]
> What leaves me skeptical is that under `Framework` there are more abstract concepts and no code (devs use code and logging only in the plugins), but it's true that debugging is something related to the whole Cat.
> 
> I'm not sure but my take is: if we will extend the `Debugging` chapter with something more, I agree with you; if under `Debugging` we'll have only `Logging`, I'll say to just put `Logging` in plugins.

yea I thought about the same thing 😸  so `Plugins` will be :)
