### ISSUE TITLE
First plugin guide, the basic guide without template

### ISSUE THREAD

**Issue by sambarza** [cheshire-cat-ai/docs#31]
from @pieroit 
> I would move the guide to plugin template usage under the registry section, or the dev section
> And have as a first guide, the basic guide (which now is under developer/plugins reference 
> The first time you write a plugin, you are not concerned with versioning and publishing... it should be just about fun and hacking

**Comment by EugenioPetulla** [comment]
@sambarza do you want help on this one? :)

**Comment by sambarza** [comment]
I have sent now the review request ;-)
