### ISSUE TITLE
Document all environment variables

### ISSUE THREAD

**Issue by Mte90** [cheshire-cat-ai/docs#33]
Just a ticket to gather what is missing and need to be documented.

## Env variables

There isn't just only the openai key but also the path for the sqllite database https://github.com/pieroit/cheshire-cat/blob/main/web/cat/db/database.py#L6

## Documentation

* document somewhere that the project saves the chat exchanges in a sqlite database

**Comment by pieroit** [comment]
Closing as duplicate of #28
