### ISSUE TITLE
Update docs with `@plugin` decorator

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/docs#34]
On the `@plugin` decorator:
- the decorated function is not piped as in hooks, it is specific and only for your plugin
- at the moment you can override `settings_schema`, `load_settings`, `save_settings`

Not worth mentioning this decorator in the get started tutorials, maybe a little reference? Or omit it and only explaining it in the "Plugin Settings" section. What do you think?

I can do this update in the next days, if you want to do it self-assign or request the issue assignation! Thanks :*

**Comment by sambarza** [comment]
I vote to keep the quickstart very easy, linear, and vote for a "more info" section in each step page, look this: https://github.com/cheshire-cat-ai/docs/pull/32#issuecomment-1737256116
