### ISSUE TITLE
Easy hook search

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/docs#36]
At the moment plugins devs can do the following to know which hooks are available and what they do:
- read the code under `cat/mad_hatter/core_plugin/hooks`
- search inside the docs

Both are useful but we need a fast and easy way to know which hook is available and for what.
Ideas until now:
- simple list of hook in the docs, with link to reference
- update the discord Cat (that can be presented on website and docs) with a plugin supporting a dedicated hook search
- go for stronger autocompletion in the IDE

**Comment by sambarza** [comment]
Additional idea, navigation from and to the flow diagram step
