### ISSUE TITLE
Add PHP client library

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/docs#42]
We could list along Python and Typescript clients, also the PHP one:

https://github.com/AlboCode/ccatphp-sdk

**Comment by pieroit** [comment]
@AlboCode

**Comment by sambarza** [comment]
Hi @AlboCode, I have just created a simple page about your PHP client library. You can preview it here: https://sambarza.github.io/cheshire-cat-ai-docs/technical/clientlib/clientlib-php/

If you like it, we can merge it into the official documentation! Feel free to suggest any changes to the page.

Thank you!

**Comment by AlboCode** [comment]
Hi, 
is perfect thanks 😃
