### ISSUE TITLE
Tools not used, troubleshooting flow

### ISSUE THREAD

**Issue by sambarza** [cheshire-cat-ai/docs#50]
Sketch a flow for troubleshooting when tools are not used.
This will be a new page under the "Guides" menu.

**Comment by pieroit** [comment]
Great idea

**Comment by sambarza** [comment]
@nicola-corbellini idea! I only reported here ;-)

**Comment by sambarza** [comment]
@nicola-corbellini if you create a draft of the flow you have in mind, then I can try to make it look "nice".

**Comment by nicola-corbellini** [comment]
I started it and forgot what I wanted to do 😂 doing it next week, sorry for the delay

**Comment by sambarza** [comment]
I'm sorry, I didn't mean to rush you.
If you prefer and think it speed up, we can talk

**Comment by nicola-corbellini** [comment]
I'm closing this since not many people are asking for the troubleshooting flowchart we discussed some time ago
