### ISSUE TITLE
HTTP endpoints page duplication

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/docs#52]
This pages both talk about the http api:
- https://cheshire-cat-ai.github.io/docs/technical/basics/cat-core/
- https://cheshire-cat-ai.github.io/docs/technical/http_reference/

The first looks more useful

**Comment by MhmoudGit** [comment]
I can help if you want to remove the second one from the docs? @pieroit

**Comment by pieroit** [comment]
Go for it @MhmoudGit ! Thanks
