### ISSUE TITLE
Add concept of plugins registry cache

### ISSUE THREAD

**Issue by sambarza** [cheshire-cat-ai/docs#54]
Plugins registry as an internal cache of published plugins, in details: plugin.json file of plugins are cached, the plugin code is not cached.
Cache invalidated each 1440 minutes

**Comment by EugenioPetulla** [comment]
I agree, too much people asks for this. I can add it here: https://cheshire-cat-ai.github.io/docs/plugins-registry/publishing-plugin/

Assign it to me :D
