### ISSUE TITLE
Recap documentation

### ISSUE THREAD

**Issue by nickprock** [cheshire-cat-ai/docs#56]
This issue is to recapitulate completed, incomplete, or partially complete documentation.

It can be used to have a page assigned for completion.

- [X] [Hello dear](https://cheshire-cat-ai.github.io/docs/)

## Quickstart:
- [X] [Introduction](https://cheshire-cat-ai.github.io/docs/quickstart/introduction/)
- [X] [Installation and First configuration](https://cheshire-cat-ai.github.io/docs/quickstart/installation-configuration/)
- [X] [Play with the Cat](https://cheshire-cat-ai.github.io/docs/quickstart/play-with-the-cat/)
- [X] [Interact using API](https://cheshire-cat-ai.github.io/docs/quickstart/interact-using-api/)
- [X] [Uploading a Document](https://cheshire-cat-ai.github.io/docs/quickstart/upload-document/)
- [X] [Preparing a Plugin](https://cheshire-cat-ai.github.io/docs/quickstart/prepare-plugin/)
- [X] [Writing the first Tool](https://cheshire-cat-ai.github.io/docs/quickstart/writing-tool/)
- [X] [Writing the first Hook](https://cheshire-cat-ai.github.io/docs/quickstart/writing-hook/)
- [X] [Stopping the Cat](https://cheshire-cat-ai.github.io/docs/quickstart/stopping-the-cat/)

## How to the Cat works:
- [ ] [The Core](https://cheshire-cat-ai.github.io/docs/conceptual/cheshire_cat/core/)
- [X] [Agent Manager](https://cheshire-cat-ai.github.io/docs/conceptual/cheshire_cat/agent/)
### The Prompts:
  - [X] [Main Prompt](https://cheshire-cat-ai.github.io/docs/conceptual/prompts/main_prompt/)
  - [X] [Instructions Prompt](https://cheshire-cat-ai.github.io/docs/conceptual/prompts/instructions/)
  - [X] [Summarization Prompt](https://cheshire-cat-ai.github.io/docs/conceptual/prompts/summarization/)
### Long term memory:
  - [X] [Introduction](https://cheshire-cat-ai.github.io/docs/conceptual/memory/long_term_memory/)
  - [X] [LTM - Episodic Memory](https://cheshire-cat-ai.github.io/docs/conceptual/memory/episodic_memory/) 
  - [X] [LTM - Declarative Memory](https://cheshire-cat-ai.github.io/docs/conceptual/memory/declarative_memory/) 
  - [X] [LTM - Procedural Memory](https://cheshire-cat-ai.github.io/docs/conceptual/memory/procedural_memory/)
- [X] [Working Memory](https://cheshire-cat-ai.github.io/docs/conceptual/memory/working_memory/)
- [X] [Rabbit Hole](https://cheshire-cat-ai.github.io/docs/conceptual/cheshire_cat/rabbit_hole/)
- [X] [Mad Hatter](https://cheshire-cat-ai.github.io/docs/conceptual/cheshire_cat/mad_hatter/)

## Admin Portal:
- [X] [Home](https://cheshire-cat-ai.github.io/docs/technical/basics/admin/admin-interface/)
- [X] [Memory](https://cheshire-cat-ai.github.io/docs/technical/basics/admin/memory/)
- [X] [Plugins](https://cheshire-cat-ai.github.io/docs/technical/basics/admin/plugins/)
- [X] [Settings](https://cheshire-cat-ai.github.io/docs/technical/basics/admin/settings/)
- [X] [Docs](https://cheshire-cat-ai.github.io/docs/technical/basics/admin/docs/)

## Plugins Registry:
- [x] [Installing a Plugin from the Registry](https://cheshire-cat-ai.github.io/docs/plugins-registry/installing-plugin/) 
- [X] [Publishing a Plugin in the Registry](https://cheshire-cat-ai.github.io/docs/plugins-registry/publishing-plugin/)
- [X] [Using the Plugin Template](https://cheshire-cat-ai.github.io/docs/plugins-registry/plugin-from-template/)

### API:
  - [X] [API Endpoints](https://cheshire-cat-ai.github.io/docs/technical/basics/cat-core/)
  - [X] [API Authentication](https://cheshire-cat-ai.github.io/docs/technical/advanced/api_auth/)
  - [X] [API Reference](https://cheshire-cat-ai.github.io/docs/technical/http_reference/)
### Plugin Reference:
  - [X] [How to write a plugin](https://cheshire-cat-ai.github.io/docs/technical/plugins/plugins/)
  - [X] [Tools](https://cheshire-cat-ai.github.io/docs/technical/plugins/tools/)
  - [X] [Hooks](https://cheshire-cat-ai.github.io/docs/technical/plugins/hooks/)
  - [X] [Plugin Settings](https://cheshire-cat-ai.github.io/docs/technical/plugins/settings/)
  - [X] [Plugin dependencies](https://cheshire-cat-ai.github.io/docs/technical/plugins/dependencies/)
### Python Reference:
- [ ] [Python Reference](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/db/)
  #### factory:
  - [X] [custom_embedder](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/factory/custom_embedder/)
  - [ ] [custom_llm](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/factory/custom_llm/)
  - [ ] [embedder](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/factory/embedder/)
  - [ ] [llm](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/factory/llm/)
- [X] [headers](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/headers/)
- [X] [log](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/log/)
  #### looking glass:
  - [X] [agent_manager](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/looking_glass/agent_manager/)
  - [ ] [callbacks](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/looking_glass/callbacks/)
  - [X] [cheshire_cat](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/looking_glass/cheshire_cat/)
  - [ ] [output_parser](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/looking_glass/output_parser/)
  - [ ] [prompts](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/looking_glass/prompts/)
### Mad Hatter:
- [ ] [decorators](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/mad_hatter/decorators/)
  #### Core plugin:
    ##### Hooks:
    - [X] [agent](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/mad_hatter/core_plugin/hooks/agent/)
    - [X] [flow](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/mad_hatter/core_plugin/hooks/flow/)
    - [X] [prompt](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/mad_hatter/core_plugin/hooks/prompt/)
    - [X] [rabbithole](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/mad_hatter/core_plugin/hooks/rabbithole/)
  - [X] [settings](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/mad_hatter/core_plugin/settings/)
  - [X] [tools](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/mad_hatter/core_plugin/tools/)
- [ ] [mad_hatter](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/mad_hatter/mad_hatter/)
- [ ] [plugin](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/mad_hatter/plugin/)
- [ ] [plugin_extractor](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/mad_hatter/plugin_extractor/)
- [ ] [registry](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/mad_hatter/registry/)
- [ ] [main](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/main/)
### Memory:
  - [X] [long_term_memory](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/memory/long_term_memory/)
  - [ ] [vector_memory](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/memory/vector_memory/) 
  - [X] [working_memory](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/memory/working_memory/)
- [X] [rabbit_hole](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/rabbit_hole/)
### Routes:
- [ ] [routes](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/)
  - [X] [base](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/base/)
  - [X] [embedder](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/embedder/)
  - [X] [llm](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/llm/)
  - [X] [memory](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/memory/)
  - [ ] [openapi](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/openapi/)
  - [X] [plugins](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/plugins/)
  - [X] [settings](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/settings/)
  - [ ] [static](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/static/)
    - [ ] [admin](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/static/admin/)
    - [ ] [auth_static](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/static/auth_static/)
    - [ ] [public](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/static/public/)
    - [ ] [static](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/static/static/)
  - [X] [upload](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/upload/)
  - [X] [websocket](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/routes/websocket/)
- [X] [utils](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/utils/)
### Debugging:
- [X] [Debug with Visual Studio Code](https://cheshire-cat-ai.github.io/docs/technical/debugging/vscode/)
### Client Libraries:
- [X] [Python](https://cheshire-cat-ai.github.io/docs/technical/clientlib/clientlib-python/)
- [X] [Typescript](https://cheshire-cat-ai.github.io/docs/technical/clientlib/clientlib-typescript/)
- [X] [PHP](https://cheshire-cat-ai.github.io/docs/technical/clientlib/clientlib-php/)
### Core Process Diagrams:
- [X] [Cat Bootstrap](https://cheshire-cat-ai.github.io/docs/technical/flows/cat-bootstrap/)
- [X] [Chatting with the Cat](https://cheshire-cat-ai.github.io/docs/technical/flows/chatting-with-the-cat/)
- [ ] [Plugins Lifecycle](https://cheshire-cat-ai.github.io/docs/technical/flows/plugins-lifecycle/)
### Advanced:
- [X] [User System](https://cheshire-cat-ai.github.io/docs/technical/advanced/user_system/)
- [X] [Testing](https://cheshire-cat-ai.github.io/docs/technical/advanced/tests/)

## Administrations:
- [X] [Architecture](https://cheshire-cat-ai.github.io/docs/administrators/architecture/)
- [X] [Environment Variables](https://cheshire-cat-ai.github.io/docs/administrators/env-variables/)

## LLM Concepts:
- [X] [Language Models](https://cheshire-cat-ai.github.io/docs/llm-concepts/llm/)
- [X] [Retrieval-Augmented Generation](https://cheshire-cat-ai.github.io/docs/llm-concepts/llm-chain/) 
- [X] [Prompt](https://cheshire-cat-ai.github.io/docs/llm-concepts/prompt/)
- [X] [Encoder](https://cheshire-cat-ai.github.io/docs/llm-concepts/encoder/)
- [X] [Vector Memory](https://cheshire-cat-ai.github.io/docs/llm-concepts/vector-memory/)

## Use Cases:
- [X] [The Cat as main product](https://cheshire-cat-ai.github.io/docs/use-cases/main-product/)
- [X] [The Cat as sidecar of your product](https://cheshire-cat-ai.github.io/docs/use-cases/side-car/)
- [ ] [The Cat as a Discord BOT](https://cheshire-cat-ai.github.io/docs/use-cases/discord-bot/)

## Guides:
- [X] [Update the Cat Core](https://cheshire-cat-ai.github.io/docs/guides/update-the-core/)
- [X] [Memory Backup](https://cheshire-cat-ai.github.io/docs/technical/advanced/memory_backup/)

## Resources:
- [X] [Video Installation](https://cheshire-cat-ai.github.io/docs/resources/video-installation/)
- [X] [Tutorials](https://cheshire-cat-ai.github.io/docs/resources/tutorials/) 
- [X] [Events](https://cheshire-cat-ai.github.io/docs/resources/events/)
- [X] [Made with the Cat](https://cheshire-cat-ai.github.io/docs/made-with-the-cat/)
- [X] [FAQ](https://cheshire-cat-ai.github.io/docs/faq/)

The issue is work in progress, if you want to be assigned a chapter comment it.

When you submit the PR remember to tag this issue and mention @sambarza and/or @EugenioPetulla

**Comment by nickprock** [comment]
I can work on LLM Concepts --> Vector Memory

**Comment by kodaline** [comment]
I would like to work on:
Long term memory -->
LTM - Episodic Memory
LTM - Declarative Memory
LTM - Procedural Memory

**Comment by EugenioPetulla** [comment]
I get the "install a plugin from the registry" one: https://cheshire-cat-ai.github.io/docs/plugins-registry/installing-plugin/

**Comment by EugenioPetulla** [comment]
Closed mine with #62 

I want to start investigate with @nicola-corbellini how the python automatic reference works in order to get rid of the page that has no reference and doesn't need to have (like the openapi route or the admin related once).

**Comment by nickprock** [comment]
Ok, I have found dociments not in index, I'm going to open a PR today.

**Comment by sambarza** [comment]
Page [Made with the Cat](https://cheshire-cat-ai.github.io/docs/made-with-the-cat/) just updated last week, added link to to the discord related channel

**Comment by nickprock** [comment]
@sambarza @EugenioPetulla do you have any ideas for the Events page?

**Comment by sambarza** [comment]
Idea was a link to the discord events but there is no direct link

![image](https://github.com/cheshire-cat-ai/docs/assets/3630051/8372a2e9-8e8b-4dde-89ba-1958e32c6148)

**Comment by nickprock** [comment]
Shared Google spreadsheet and something like Timemapper?

**Comment by nickprock** [comment]
I think that we can close the issue. Thanks ❤️
