### ISSUE TITLE
Big lie in save settings documentation

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/docs#84]
[Here](https://cheshire-cat-ai.github.io/docs/technical/plugins/settings/#access-settings-from-within-your-plugin) we say about saving settings:

```
where settings is a dictionary, a JSON schema or a Pydantic BaseModel describing your plugin's settings.
```

In reality we only support a simple dictionary

![image](https://github.com/cheshire-cat-ai/docs/assets/6328377/e9a9f680-439a-4ecb-83d7-8518d020dfac)

**Comment by nicola-corbellini** [comment]
ops, forgot, ty!
