### ISSUE TITLE
Empty plugins not in plugins page

### ISSUE THREAD

**Issue by sambarza** [cheshire-cat-ai/docs#88]
The empty plugins seems not listed in plugin page, confirm and update page:
https://cheshire-cat-ai.github.io/docs/quickstart/prepare-plugin/

**Comment by kodaline** [comment]
Hi @sambarza , what do you mean with "empty plugins"?

**Comment by sambarza** [comment]
Quickstart in docs asks to create an empty plugin, activate it and then create the .py file however the plugin was not listed in plugin page if it do not contains .py files, there is a log during bootstrap:
[2024-09-12 21:50:32.004] ERROR  cat.mad_hatter.mad_hatter.MadHatter.load_plugin::133 
2024-09-12 23:50:32 cheshire_cat_core  | "cat/plugins/new-plugin/ does not contain any python files. Cannot create Plugin."

It's correct behaviour to not show the plugin.

Quickstart already updated, now it asks to create an emtpy .py file and then fill it.
