### ISSUE TITLE
Hook discoverability and practical examples

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/docs#90]
Hooks are difficult to find, not because they are not present in docs, but because devs cannot know in advance what hooks does what.
Let' try to give more use cases and practical examples and improve their discoverability.
A particular focus should be given to `most used` hooks.

Reunion needed on this!
We can start with just 2 or 3 hooks and see how it goes

**Comment by EugenioPetulla** [comment]
I like a lot the organization of WP in doing this.

There is a page that talks about Actions and gives you a lot of information about how to use them and how to discover them into the code (find a do_action funcion). In the same page there are also list of hooks for specific fields so everithing is in the same place. This invites the reader to further investigate but also gives him an ordered list of the most useful hooks he can use instantly.

https://codex.wordpress.org/Plugin_API/Action_Reference

**Comment by nicola-corbellini** [comment]
I'll close this one, if you think more should be added we can open it again

**Comment by pieroit** [comment]
@nicola-corbellini many kudos for how you handled this, it's awesome
