### ISSUE TITLE
Add links to the available hooks table

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/docs#94]
In [this table](https://cheshire-cat-ai.github.io/docs/technical/plugins/hooks/#available-hooks) there are the `note` admonitions with links pointing to nowhere. The link should be added to the related Python reference documentation and, where available, to the reference plugin github repo.

**Comment by ZSThai** [comment]
I'm a new user, can you provide me more information about this issue? Can I try to solve this issue?

**Comment by nicola-corbellini** [comment]
Sure! 
As you can see from the image, in the "Other resources" box there are some items listed (I notice now the typo in the image)
![immagine](https://github.com/cheshire-cat-ai/docs/assets/67009524/d946cc72-d80c-445c-a397-1b9e8bbe6531)

each box has at least the "Python reference" item, which should be linked to the technical documentation of the hook at hand. 
E.g. the python ref of the `before_cat_reads_message` (the one in the screenshot) is [here](https://cheshire-cat-ai.github.io/docs/technical/API_Documentation/mad_hatter/core_plugin/hooks/flow/#cat.mad_hatter.core_plugin.hooks.flow.before_cat_reads_message).
In general, all the hooks docs can be found under `Developers -> Python Reference -> mad_hatter -> core_plugin -> hooks`

The other items should point to specific plugin repos. Most of them can be found [here](https://github.com/orgs/Furrmidable-Crew/repositories) (e.g. hyde, summarization, C.A.T. and stay on topic). 
The others are:
- [Rabbithole segmentation plugin](https://github.com/team-sviluppo/cc_rabbithole_segmentation)
- [Debugger plugin](https://github.com/sambarza/cc-vscode-debugpy)

If you have any doubt or you need some link I didn't provide you, please let me know
